title:              Renatojobal Blog
email:              renatojobal@gmail.com
description:        A Blog for general purposes
author:             Renato Balcázar
baseurl:            "/blog"
url:                "https://www.renatojobal.com"

# Social Profiles
twitter_username:   renatojobal
github_username:    renatojobal
facebook_username:  renatojobal
instagram_username: renatojobal
linkedin_username:  renatojobal

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
